
package myprojects;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Imon
 */
public class Guessing extends javax.swing.JInternalFrame {
  public int i1;

    public Guessing() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbed = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Game1panel = new javax.swing.JPanel();
        JB_1_1 = new javax.swing.JButton();
        JB_1_2 = new javax.swing.JButton();
        JB_1_3 = new javax.swing.JButton();
        JL_1_1 = new javax.swing.JLabel();
        javax.swing.JLabel JL_1_2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Game2panel = new javax.swing.JPanel();
        JB_2_1 = new javax.swing.JButton();
        JB_2_2 = new javax.swing.JButton();
        JB_2_3 = new javax.swing.JButton();
        JB_2_4 = new javax.swing.JButton();
        JL_2_1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jP_3 = new javax.swing.JPanel();
        JB_3_1 = new javax.swing.JButton();
        JB_3_2 = new javax.swing.JButton();
        JB_3_3 = new javax.swing.JButton();
        JB_3_4 = new javax.swing.JButton();
        JB_3_5 = new javax.swing.JButton();
        JL_3_1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Game4panel = new javax.swing.JPanel();
        JB_4_1 = new javax.swing.JButton();
        JB_4_2 = new javax.swing.JButton();
        JB_4_3 = new javax.swing.JButton();
        JB_4_4 = new javax.swing.JButton();
        JB_4_5 = new javax.swing.JButton();
        JL_4_2 = new javax.swing.JLabel();
        jJL_4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Game5panel = new javax.swing.JPanel();
        JB_5_1 = new javax.swing.JButton();
        JB_5_2 = new javax.swing.JButton();
        JB_5_3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JL_5_1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Guessing Game");

        jTabbed.setBackground(new java.awt.Color(255, 255, 0));

        Game1panel.setBackground(new java.awt.Color(102, 255, 102));

        JB_1_1.setBackground(new java.awt.Color(204, 204, 204));
        JB_1_1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        JB_1_1.setForeground(new java.awt.Color(255, 0, 51));
        JB_1_1.setText("One Hundred Plus");
        JB_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_1_1ActionPerformed(evt);
            }
        });

        JB_1_2.setBackground(new java.awt.Color(102, 102, 102));
        JB_1_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JB_1_2.setForeground(new java.awt.Color(51, 51, 255));
        JB_1_2.setText("Two Hundred Plus");
        JB_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_1_2ActionPerformed(evt);
            }
        });

        JB_1_3.setBackground(new java.awt.Color(51, 51, 51));
        JB_1_3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        JB_1_3.setForeground(new java.awt.Color(255, 0, 255));
        JB_1_3.setText("Three Hundred Plus");
        JB_1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_1_3ActionPerformed(evt);
            }
        });

        JL_1_1.setBackground(new java.awt.Color(51, 255, 51));
        JL_1_1.setFont(new java.awt.Font("Rockwell Condensed", 0, 48)); // NOI18N
        JL_1_1.setForeground(new java.awt.Color(204, 0, 0));
        JL_1_1.setText(" Round 1: Guess Now . .");

        JL_1_2.setBackground(new java.awt.Color(102, 51, 255));
        JL_1_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Banana.jpg"))); // NOI18N
        JL_1_2.setLabelFor(JB_1_1);

        jLabel1.setBackground(new java.awt.Color(255, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("How many bananas?");

        javax.swing.GroupLayout Game1panelLayout = new javax.swing.GroupLayout(Game1panel);
        Game1panel.setLayout(Game1panelLayout);
        Game1panelLayout.setHorizontalGroup(
            Game1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Game1panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Game1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Game1panelLayout.createSequentialGroup()
                        .addGroup(Game1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(JL_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Game1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JL_1_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Game1panelLayout.setVerticalGroup(
            Game1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Game1panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(JL_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Game1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Game1panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Game1panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(JB_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game1panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Game1panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbed.addTab("Round  1", jPanel1);

        Game2panel.setBackground(new java.awt.Color(255, 102, 255));
        Game2panel.setBorder(new javax.swing.border.MatteBorder(null));
        Game2panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JB_2_1.setBackground(new java.awt.Color(102, 255, 102));
        JB_2_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_2_1.setText("2");
        JB_2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_2_1ActionPerformed(evt);
            }
        });

        JB_2_2.setBackground(new java.awt.Color(255, 51, 255));
        JB_2_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_2_2.setText("3");
        JB_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_2_2ActionPerformed(evt);
            }
        });

        JB_2_3.setBackground(new java.awt.Color(255, 255, 0));
        JB_2_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_2_3.setText("4");
        JB_2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_2_3ActionPerformed(evt);
            }
        });

        JB_2_4.setBackground(new java.awt.Color(0, 255, 255));
        JB_2_4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_2_4.setText("5");
        JB_2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_2_4ActionPerformed(evt);
            }
        });

        JL_2_1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL_2_1.setForeground(new java.awt.Color(255, 0, 0));
        JL_2_1.setText(" Round 2: Guess Now . .");

        jLabel2.setBackground(new java.awt.Color(51, 0, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("How many pencils do you have? ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.jpg"))); // NOI18N

        javax.swing.GroupLayout Game2panelLayout = new javax.swing.GroupLayout(Game2panel);
        Game2panel.setLayout(Game2panelLayout);
        Game2panelLayout.setHorizontalGroup(
            Game2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Game2panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(JB_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(JB_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(JB_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(JB_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game2panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Game2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game2panelLayout.createSequentialGroup()
                        .addComponent(JL_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game2panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64))))
        );
        Game2panelLayout.setVerticalGroup(
            Game2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game2panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Game2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Game2panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(Game2panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                .addGroup(Game2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_2_1)
                    .addComponent(JB_2_2)
                    .addComponent(JB_2_3)
                    .addComponent(JB_2_4))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game2panel, javax.swing.GroupLayout.PREFERRED_SIZE, 784, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game2panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbed.addTab("Round 2", jPanel2);

        jP_3.setBackground(new java.awt.Color(153, 153, 255));

        JB_3_1.setBackground(new java.awt.Color(204, 255, 255));
        JB_3_1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_3_1.setText("10");
        JB_3_1.setPreferredSize(new java.awt.Dimension(74, 60));
        JB_3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3_1ActionPerformed(evt);
            }
        });

        JB_3_2.setBackground(new java.awt.Color(153, 255, 255));
        JB_3_2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_3_2.setText("20");
        JB_3_2.setPreferredSize(new java.awt.Dimension(74, 60));
        JB_3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3_2ActionPerformed(evt);
            }
        });

        JB_3_3.setBackground(new java.awt.Color(51, 255, 255));
        JB_3_3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_3_3.setText("30");
        JB_3_3.setPreferredSize(new java.awt.Dimension(74, 60));
        JB_3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3_3ActionPerformed(evt);
            }
        });

        JB_3_4.setBackground(new java.awt.Color(0, 255, 255));
        JB_3_4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_3_4.setText("40");
        JB_3_4.setPreferredSize(new java.awt.Dimension(74, 60));
        JB_3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3_4ActionPerformed(evt);
            }
        });

        JB_3_5.setBackground(new java.awt.Color(0, 204, 204));
        JB_3_5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JB_3_5.setText("50");
        JB_3_5.setPreferredSize(new java.awt.Dimension(74, 60));
        JB_3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3_5ActionPerformed(evt);
            }
        });

        JL_3_1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL_3_1.setForeground(new java.awt.Color(0, 0, 255));
        JL_3_1.setText(" Round 3: Guess Now .");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("How many Book?");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Book.jpg"))); // NOI18N

        javax.swing.GroupLayout jP_3Layout = new javax.swing.GroupLayout(jP_3);
        jP_3.setLayout(jP_3Layout);
        jP_3Layout.setHorizontalGroup(
            jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(124, 124, 124))
            .addGroup(jP_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jP_3Layout.createSequentialGroup()
                .addGroup(jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JB_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_3_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_3_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(jP_3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(JB_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jP_3Layout.setVerticalGroup(
            jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(JL_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_3Layout.createSequentialGroup()
                        .addGroup(jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jP_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB_3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbed.addTab("Round 3", jPanel3);

        Game4panel.setBackground(new java.awt.Color(153, 255, 255));
        Game4panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Game4panelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        JB_4_1.setBackground(new java.awt.Color(0, 255, 153));
        JB_4_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JB_4_1.setForeground(new java.awt.Color(255, 51, 51));
        JB_4_1.setText("1");
        JB_4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_4_1ActionPerformed(evt);
            }
        });

        JB_4_2.setBackground(new java.awt.Color(51, 255, 102));
        JB_4_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JB_4_2.setForeground(new java.awt.Color(255, 51, 51));
        JB_4_2.setText("2");
        JB_4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_4_2ActionPerformed(evt);
            }
        });

        JB_4_3.setBackground(new java.awt.Color(102, 255, 102));
        JB_4_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JB_4_3.setForeground(new java.awt.Color(255, 51, 51));
        JB_4_3.setText("3");
        JB_4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_4_3ActionPerformed(evt);
            }
        });

        JB_4_4.setBackground(new java.awt.Color(153, 255, 153));
        JB_4_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JB_4_4.setForeground(new java.awt.Color(255, 51, 51));
        JB_4_4.setText("4");
        JB_4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_4_4ActionPerformed(evt);
            }
        });

        JB_4_5.setBackground(new java.awt.Color(204, 255, 204));
        JB_4_5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JB_4_5.setForeground(new java.awt.Color(255, 51, 51));
        JB_4_5.setText("5");
        JB_4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_4_5ActionPerformed(evt);
            }
        });

        JL_4_2.setBackground(new java.awt.Color(51, 255, 51));
        JL_4_2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL_4_2.setForeground(new java.awt.Color(255, 0, 0));
        JL_4_2.setText(" Round 4: Guess now");

        jJL_4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jJL_4.setForeground(new java.awt.Color(255, 0, 255));
        jJL_4.setText("How many products in the box ?");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close-box.jpg"))); // NOI18N

        javax.swing.GroupLayout Game4panelLayout = new javax.swing.GroupLayout(Game4panel);
        Game4panel.setLayout(Game4panelLayout);
        Game4panelLayout.setHorizontalGroup(
            Game4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Game4panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(Game4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JB_4_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(JB_4_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_4_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_4_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_4_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(Game4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Game4panelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addGap(62, 62, 62))
                    .addGroup(Game4panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JL_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game4panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jJL_4, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        Game4panelLayout.setVerticalGroup(
            Game4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Game4panelLayout.createSequentialGroup()
                .addComponent(jJL_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Game4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Game4panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Game4panelLayout.createSequentialGroup()
                        .addComponent(JL_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game4panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game4panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbed.addTab("Round 4", jPanel4);

        Game5panel.setBackground(new java.awt.Color(153, 153, 153));

        JB_5_1.setBackground(new java.awt.Color(204, 0, 204));
        JB_5_1.setText("1123");
        JB_5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_5_1ActionPerformed(evt);
            }
        });

        JB_5_2.setBackground(new java.awt.Color(204, 0, 204));
        JB_5_2.setText("2357");
        JB_5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_5_2ActionPerformed(evt);
            }
        });

        JB_5_3.setBackground(new java.awt.Color(255, 0, 255));
        JB_5_3.setText("4522");
        JB_5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_5_3ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magic box.jpg"))); // NOI18N

        JL_5_1.setBackground(new java.awt.Color(51, 255, 51));
        JL_5_1.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        JL_5_1.setForeground(new java.awt.Color(255, 0, 0));
        JL_5_1.setText(" Round 5: ");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Find out the password to open this box?");

        javax.swing.GroupLayout Game5panelLayout = new javax.swing.GroupLayout(Game5panel);
        Game5panel.setLayout(Game5panelLayout);
        Game5panelLayout.setHorizontalGroup(
            Game5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Game5panelLayout.createSequentialGroup()
                .addGroup(Game5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Game5panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JB_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Game5panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JL_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game5panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        Game5panelLayout.setVerticalGroup(
            Game5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Game5panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Game5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Game5panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Game5panelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(JL_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Game5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB_5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game5panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Game5panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbed.addTab("Round 5", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbed)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbed)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3_5ActionPerformed
        // TODO add your handling code here:
        inco3(50);
    }//GEN-LAST:event_JB_3_5ActionPerformed

    private void JB_3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3_4ActionPerformed
        // TODO add your handling code here:
        inco3(40);
    }//GEN-LAST:event_JB_3_4ActionPerformed

    private void JB_3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3_3ActionPerformed
        // TODO add your handling code here:
        inco3(30);
    }//GEN-LAST:event_JB_3_3ActionPerformed

    private void JB_3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3_2ActionPerformed
        // TODO add your handling code here:
        inco3(20);
    }//GEN-LAST:event_JB_3_2ActionPerformed

    private void JB_3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3_1ActionPerformed
        // TODO add your handling code here:
        inco3(10);
    }//GEN-LAST:event_JB_3_1ActionPerformed

    private void JB_2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_2_4ActionPerformed
        // TODO add your handling code here:
        inco2(5);
    }//GEN-LAST:event_JB_2_4ActionPerformed

    private void JB_2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_2_3ActionPerformed
        // TODO add your handling code here:
        inco2(4);
    }//GEN-LAST:event_JB_2_3ActionPerformed

    private void JB_2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_2_2ActionPerformed
        // TODO add your handling code here:
        inco2(3);
    }//GEN-LAST:event_JB_2_2ActionPerformed

    private void JB_2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_2_1ActionPerformed
        // TODO add your handling code here:
        inco2(2);
    }//GEN-LAST:event_JB_2_1ActionPerformed

    private void JB_1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_1_3ActionPerformed
        // TODO add your handling code here:
        inco(3);
        i1=i1+1;
    }//GEN-LAST:event_JB_1_3ActionPerformed

    private void JB_1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_1_2ActionPerformed
        // TODO add your handling code here:
        inco(2);
        i1=i1+1;
    }//GEN-LAST:event_JB_1_2ActionPerformed

    private void JB_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_1_1ActionPerformed
        // TODO add your handling code here:
        inco(1);
        i1=i1+1;
    }//GEN-LAST:event_JB_1_1ActionPerformed

    private void Game4panelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Game4panelAncestorAdded
        // TODO add your handling code here:
        inco4(0);
    }//GEN-LAST:event_Game4panelAncestorAdded

    private void JB_4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_4_1ActionPerformed
        // TODO add your handling code here:
        inco4(1);
      
    }//GEN-LAST:event_JB_4_1ActionPerformed

    private void JB_4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_4_2ActionPerformed
        // TODO add your handling code here:
         inco4(2);
        
    }//GEN-LAST:event_JB_4_2ActionPerformed

    private void JB_4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_4_3ActionPerformed
        // TODO add your handling code here:
         inco4(3);
           
    }//GEN-LAST:event_JB_4_3ActionPerformed

    private void JB_4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_4_4ActionPerformed
        // TODO add your handling code here:
         inco4(4);
         
    }//GEN-LAST:event_JB_4_4ActionPerformed

    private void JB_4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_4_5ActionPerformed
        // TODO add your handling code here:
         inco4(5);
          
    }//GEN-LAST:event_JB_4_5ActionPerformed

    private void JB_5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_5_1ActionPerformed
        // TODO add your handling code here:
          inco5(1);
    }//GEN-LAST:event_JB_5_1ActionPerformed

    private void JB_5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_5_2ActionPerformed
        // TODO add your handling code here:
          inco5(2);
    }//GEN-LAST:event_JB_5_2ActionPerformed

    private void JB_5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_5_3ActionPerformed
        // TODO add your handling code here:
         inco5(3);
    }//GEN-LAST:event_JB_5_3ActionPerformed
   
  //____________________________Round 1#_______________________________  
    public void inco(int x)
   {
   ImageIcon img =new ImageIcon("6.png");
int g = x;
 Random ran =new Random();
 int r =ran.nextInt(3)+1;
if(r==g){
 // document.write("you win "+g+" RANDOM NUMBER IS " +r+"<br/>");
 //System.out.println(" guessing Win "+g);
 JL_1_1.setText("congratulations! YouWin.");
   
 //L_T2.setText(li);
}
else{
  // System.out.println("lose Random number  "+r );
  //document.write("you los "+g+" RANDOM NUMBER IS " +r+"<br/>");
  //l++;
  int ra =100*r;
   JL_1_1.setText("False! It is a "+ra+"+");
}
//document.write("Tolal win: "+w+"<br/>");
//System.out.print(" \n win ");
//document.write("Tolal los: "+l+"<br/>");  
   }  
 //____________Round 2#______________________________________
    private void inco2(int y)
    {
       
        int g = y;
  Random ran =new Random();
   int r =ran.nextInt(4)+2;
   if(r==g){
  JL_2_1.setText("Good Guessing....  YouWin!");

}
else{
 
  //int ra =100*r;
   JL_2_1.setText("Wrong!  "+r+"is a number.");
}
    }
    //_________________________Round 3#___________________
    public void inco3(int z){
               int g = z/10;
  Random ran =new Random();
   int r =ran.nextInt(4)+1;
   if(r==g){
 JL_3_1.setText("Good Answer.. :)  YouWin! ");
}
else{
 
   int ra =10*r;
   JL_3_1.setText("Wrong! Answer "+ra+" :(");
}
        
    }
    //_________________________Round4#_______________________________
 
    public void  inco4(int q){
             int w=0;
             int d=0;
        int g = q;
  Random ran =new Random();
   int r =ran.nextInt(6)+1;
   if(r==g){
  JL_4_2.setText("YouWin!");  
}
else{
 
  //int ra =100*r;
   JL_4_2.setText("Wrong! ");
} 
   
    }
 //____________________________round5#_____________________________
        public void  inco5(int t){
             int w=0;
             int d=0;
        int g = t;
  Random ran =new Random();
   int r =ran.nextInt(3)+1;
   if(r==g){
  JL_5_1.setText("Win!");  
}
else{
 
  //int ra =100*r;
   JL_5_1.setText("Try again");
} 
   
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Game1panel;
    public javax.swing.JPanel Game2panel;
    private javax.swing.JPanel Game4panel;
    private javax.swing.JPanel Game5panel;
    private javax.swing.JButton JB_1_1;
    private javax.swing.JButton JB_1_2;
    private javax.swing.JButton JB_1_3;
    private javax.swing.JButton JB_2_1;
    private javax.swing.JButton JB_2_2;
    private javax.swing.JButton JB_2_3;
    private javax.swing.JButton JB_2_4;
    private javax.swing.JButton JB_3_1;
    private javax.swing.JButton JB_3_2;
    private javax.swing.JButton JB_3_3;
    private javax.swing.JButton JB_3_4;
    private javax.swing.JButton JB_3_5;
    private javax.swing.JButton JB_4_1;
    private javax.swing.JButton JB_4_2;
    private javax.swing.JButton JB_4_3;
    private javax.swing.JButton JB_4_4;
    private javax.swing.JButton JB_4_5;
    private javax.swing.JButton JB_5_1;
    private javax.swing.JButton JB_5_2;
    private javax.swing.JButton JB_5_3;
    private javax.swing.JLabel JL_1_1;
    private javax.swing.JLabel JL_2_1;
    private javax.swing.JLabel JL_3_1;
    private javax.swing.JLabel JL_4_2;
    private javax.swing.JLabel JL_5_1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jJL_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jP_3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbed;
    // End of variables declaration//GEN-END:variables
}
